version: "2"

run:
  timeout: 5m
  tests: true

linters:
  enable:
    - govet
    - errcheck
    - staticcheck
    - ineffassign

  exclusions:
    rules:
      - path: '(.+)_test\.go'
        linters:
          - errcheck
